---
title: "C4P Presentation"
author: "Conor Tompkins"
date: "April 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

register_google(key = "AIzaSyBTJxUwvLUY3GiJgJ5cBSLEb_n1TPRjJPE")
```

#Packages
##Simple Features {sf}

##{tidycensus}

##{ggmap}


Get your census API key: https://api.census.gov/data/key_signup.html

configure environment
```{r}
library(tidycensus)
library(tidyverse)
library(sf)
library(tigris)
library(lwgeom)
library(ggmap)
library(janitor)

theme_set(theme_bw())

options(tigris_use_cache = TRUE)

census_api_key("a16f3636406d2b544871e2ae49bb318c3ddcacba")
```


load variables
```{r}
variables_acs <- load_variables(2017, "acs5", cache = TRUE)

variables_acs
```
```{r}
variables_dec <- load_variables(2010, "sf1", cache = TRUE)

variables_dec
```
```{r}
states <- get_decennial(geography = "state",
                           variables = c(total_pop = "P001001"),
                           #state = "PA", county = "Allegheny County",
                           geometry = TRUE)

states %>% 
  filter(NAME != "Alaska",
         NAME != "Hawaii") %>% 
  ggplot(aes(fill = value)) +
  geom_sf() +
  scale_fill_viridis_c()
```

```{r}
pennsylvania <- get_decennial(geography = "county",
                           variables = c(total_pop = "P001001"),
                           state = "PA",
                           geometry = TRUE,
                           output = "wide")

pennsylvania %>% 
  ggplot(aes(fill = total_pop)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c()
```

```{r}
allegheny <- pennsylvania %>% 
  filter(str_detect(NAME, "Allegheny"))

pennsylvania %>% 
  ggplot() +
  geom_sf(aes(fill = total_pop), color = NA) +
  geom_sf(data = allegheny, color = "white", linetype = 2, size = 1, alpha = 0) +
  scale_fill_viridis_c()
```

don't use
load census block data for total pop
```{r eval=FALSE, include=FALSE}
allegheny <- get_decennial(geography = "block",
                           variables = c(total_pop = "P001001"),
                           state = "PA", county = "Allegheny County",
                           geometry = TRUE)
```

don't use
graph
```{r eval=FALSE, include=FALSE}
allegheny %>% 
  ggplot(aes(fill = value)) +
  geom_sf(color = NA) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c("Total Population")
```

download demographic data for census blocks
```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

#note that this data is long, not wide
allegheny <- get_decennial(geography = "tract", variables = racevars, 
                        state = "PA", county = "Allegheny County", geometry = TRUE,
                        summary_var = "P001001") 
```
```{r}
allegheny <- allegheny %>% 
  mutate(pct = 100 * value / summary_value)
```

graph
```{r}
allegheny %>% 
  ggplot(aes(fill = pct)) +
  geom_sf(color = NA) +
  facet_wrap(~variable) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c()
```

make rivers show up
```{r}
st_erase <- function(x, y) {
  st_difference(x, st_union(st_combine(y)))
}

allegheny_water <- area_water("PA", "Allegheny County", class = "sf")

allegheny %>% 
  ggplot() +
  geom_sf() +
  geom_sf(data = allegheny_water, fill = "blue")

allegheny_erase <- st_erase(allegheny, alegheny_water)
```
```{r, eval=FALSE}
allegheny_erase %>% 
  ggplot(aes(fill = pct)) +
  geom_sf(color = NA) +
  facet_wrap(~variable) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c()
```

overlay [city boundaries](https://catalog.data.gov/dataset/pittsburgh-city-boundary-cbe8f) over same graph
```{r}
city_pgh <- st_read("Pittsburgh_City_Boundary/Pittsburgh_City_Boundary.shp")

allegheny %>% 
  ggplot() +
  geom_sf(aes(fill = pct), color = NA) +
  geom_sf(data = city_pgh, color = "white", line_type = 2, size = 1, alpha = 0) +
  facet_wrap(~variable) +
  coord_sf(crs = 26915) + 
  scale_fill_viridis_c()

```


#WPRDC fire data
```{r eval=FALSE, include=FALSE}
pgh_fire_shp <- st_read("Allegheny_County_Census_Block_Groups_2016/Allegheny_County_Census_Block_Groups_2016.shp")

pgh_fire_districts <- st_read("Fire_Districts/Fire_Districts.shp")

pgh_fire <- read_csv("911-fire-dispatches.csv", col_types = cols(.default = "c")) 
  
pgh_fire <- pgh_fire %>% 
  count(GEOID, sort = TRUE) %>% 
  filter(GEOID != "420034520001")

pgh_fire_shp <- pgh_fire_shp %>% 
  #semi_join(pgh_fire) %>% 
  left_join(pgh_fire)

pgh_fire_shp %>% 
  ggplot() +
  geom_sf(aes(fill = n), color = NA) +
  scale_fill_viridis_c()

pgh_fire_districts %>% 
  ggplot() +
  geom_sf()
```

311 data
[pittsburgh wards](https://catalog.data.gov/dataset/pittsburgh-wards)
```{r}
df_311 <- read_csv("https://data.wprdc.org/datastore/dump/76fda9d0-69be-4dd5-8108-0de7907fc5a4")

wards <- st_read("PGHWards/PGHWards.shp")

wards %>% 
  ggplot() +
  geom_sf()

ward_labels <- wards %>% 
  st_centroid() %>% 
  st_coordinates() %>% 
  as_tibble() %>% 
  clean_names()

df_311_count <- df_311 %>% 
  count(WARD, sort = TRUE)

ward_311 <- wards %>% 
  left_join(df_311_count, by = c("ward" = "WARD")) %>%
  bind_cols(ward_labels)

ward_311 %>% 
  ggplot() +
  geom_sf(aes(fill = n), color = NA) +
  geom_label(aes(x, y, label = ward), size = 3) +
  scale_fill_viridis_c("Number of 311 requests")
```

```{r}
pgh_map <- get_map(location = "Pittsburgh, PA", zoom = 12)

ggmap(pgh_map) 

ggmap(pgh_map) +
  geom_sf(data = ward_311, aes(fill = n), inherit.aes = FALSE, color = NA, alpha = .7) +
  coord_sf(crs = st_crs(4326)) +
  scale_fill_viridis_c("Number of 311 requests")
```

##Links

*https://walkerke.github.io/tidycensus/articles/basic-usage.html
*https://walkerke.github.io/tidycensus/reference/get_acs.html
*https://walkerke.github.io/tidycensus/articles/spatial-data.html
*https://walkerke.github.io/tidycensus/articles/other-datasets.html
*https://cengel.github.io/R-spatial/mapping.html
*https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html
*https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html
*https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-3.html
*google maps API key: https://cloud.google.com/maps-platform/
*https://lucidmanager.org/geocoding-with-ggmap/
