---
title: "ALlegheny County Tract Profiling"
author: "Conor Tompkins"
date: "July 24, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(broom)
library(ggfortify)
library(viridis)
options(tigris_use_cache = TRUE)
census_api_key("a16f3636406d2b544871e2ae49bb318c3ddcacba")

theme_set(theme_minimal())

census_vars <- load_variables(2010, "sf1", cache = TRUE)
```

```{r}
vars_demo <- c(white = "P0050003", 
          black = "P0050004", 
          asian = "P0050006", 
          hispanic = "P0040003")
#age vars men and women
#P0120003:P0120049

get_decennial(geography = "tract", 
                           variables = vars_demo,
                           state = "PA", 
                           county = "Allegheny", 
                           geometry = FALSE,
                           summary_var = "P0010001") %>% 
  arrange(GEOID) %>% 
  mutate(value = value / summary_value) %>% 
  select(-summary_value) %>% 
  spread(variable, value) %>% 
  rename_at(vars("white", "black", "asian", "hispanic"), funs(str_c("percent_", .))) -> allegheny_demographics

allegheny_demographics <- replace(allegheny_demographics, is.na(allegheny_demographics), 0)

vars_housing <- c(units_owned_loan = "H0110002",
          units_owned_entire = "H0110003",
          units_rented = "H0110004")

get_decennial(geography = "tract", 
                           variables = vars_housing,
                           state = "PA", 
                           county = "Allegheny", 
                           geometry = FALSE,
                           summary_var = "H0110001") %>% 
  arrange(GEOID) %>% 
  mutate(value = value / summary_value) %>% 
  select(-summary_value) %>% 
  spread(variable, value) %>% 
  rename_at(vars("units_owned_entire", "units_owned_loan", "units_rented"), funs(str_c("percent_", .))) -> allegheny_housing

allegheny_housing <- replace(allegheny_housing, is.na(allegheny_housing), 0)

get_decennial(geography = "tract", 
                           variables = vars_housing,
                           state = "PA", 
                           county = "Allegheny", 
                           geometry = TRUE) %>% 
  select(-c(variable, value)) -> allegheny_geo
```

```{r}
str(allegheny_housing)
str(allegheny_demographics)

allegheny_geo %>% 
  left_join(allegheny_housing) %>% 
  left_join(allegheny_demographics) %>% 
  mutate(id = str_c(GEOID, NAME, sep = "|")) %>% 
  distinct() -> allegheny

allegheny %>% 
  count(id, sort = TRUE)
```


```{r}
allegheny %>%
  select(-c(id, GEOID)) %>% 
  st_set_geometry(NULL) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "NAME") -> allegheny_pca
```

```{r}
allegheny_pca %>% 
  prcomp(scale = TRUE) -> pc
```

```{r}
pc %>% 
  tidy() %>% 
  head()
```

```{r}
pc %>% 
  tidy("pcs")
```

```{r}
pc %>% 
  augment(data = allegheny_pca) %>% 
  as_tibble() -> au

au %>% 
  head()
```

```{r}
pc %>% 
  tidy("pcs") %>%
  select(-std.dev) %>% 
  gather(measure, value, -PC) %>% 
    ggplot(aes(PC, value)) +
    geom_line() +
    geom_point() +
    facet_wrap(~measure) +
    labs(title = "Variance explained by each principal component",
         x = "Principal Component",
         y = NULL) +
    scale_x_continuous(breaks = 1:7)
```

```{r}
allegheny %>% 
  select(-c(id, GEOID)) %>% 
  st_set_geometry(NULL) %>% 
  nest() %>% 
  mutate(pca = map(data, ~ prcomp(.x %>% select(-NAME), 
                                  center = TRUE, scale = TRUE)),
         pca_aug = map2(pca, data, ~augment(.x, data = .y))) -> allegheny_pca2
```

```{r}
allegheny_pca2 %>% 
mutate(
    pca_graph = map2(
      .x = pca,
      .y = data,
      ~ autoplot(.x, loadings = TRUE, loadings.label = TRUE,
                 loadings.label.repel = TRUE,
                 data = .y) +
        theme_bw() +
        labs(x = "Principal Component 1",
             y = "Principal Component 2",
             title = "First two principal components of PCA on Allegheny County Census data")
    )
  ) %>%
  pull(pca_graph)
```

```{r}
au %>% 
  rename(NAME = .rownames) %>% 
  gather(variable, value, -c(NAME)) -> au_long

st_erase <- function(x, y) {
  st_difference(x, st_union(st_combine(y)))
}

allegheny_water <- area_water("PA", "Allegheny", class = "sf")

allegheny_geo <- st_erase(allegheny_geo, allegheny_water)


allegheny_geo %>% 
  left_join(au %>% rename(NAME = .rownames)) %>% 
  #gather(variable, value, contains("percent")) %>% 
  gather(pc, pc_value, contains(".fitted")) -> allegheny_pca_map

allegheny_pca_map %>% 
  filter(pc == ".fittedPC1" | pc == "fittedPC2") -> test 

allegheny_pca_map %>% 
  #filter(pc == ".fittedPC3") %>% 
  ggplot(aes(fill = pc_value, color = pc_value)) + 
  geom_sf() + 
  facet_wrap(~pc) +
  coord_sf(crs = 26911) + 
  scale_fill_viridis("Principal component value", option = "magma") + 
  scale_color_viridis("Principal component value", option = "magma") +
  labs(title = "Allegheny County",
       subtitle = "American Community Survey") +
  theme(axis.text = element_blank())
```